### ISSUE TITLE
User Deatils In User Popouts

### ISSUE THREAD

**Issue by Soft-Bred** [Loremly/Nebula#1]
Idk if this is a bug, but it would be nice to either have user details implemented (could be an on or off switch in settings), or have support for it 😔 
![image](https://user-images.githubusercontent.com/60551230/131598527-605ededa-9fd4-4ec9-9b90-0757bc7a406f.png)
![image](https://user-images.githubusercontent.com/60551230/131598723-e6159a5e-84b4-4723-9a76-0f8691c47a2b.png)

**Comment by Loremly** [comment]
I'll try my best
