### ISSUE TITLE
Changing server panel

### ISSUE THREAD

**Issue by ElijahGives** [Loremly/Nebula#10]
![image](https://user-images.githubusercontent.com/57592789/142500458-2c66f264-73e2-491e-9e90-a22c49ac43a2.png)
I'm wondering if its possible to change ^ above back to original (on the side.)
If there's a setting or config/something, let me know or if you can add that maybe.

**Comment by Loremly** [comment]
Will put this in the next update

**Comment by Loremly** [comment]
Solved in 5.3.8 Update. Please Update Nebula! Enjoy
