### ISSUE TITLE
Discovery Tab

### ISSUE THREAD

**Issue by TheRealGWJosh** [Loremly/Nebula#11]
**Describe the bug**
User Panel and Header Not Positioned Right.

**To Reproduce**
1. Go to 'Servers'
2. Scroll down to 'Discovery'
3. Click on 'The Discovery Button'

**Expected behavior**
Header and User Panel Should Be Positioned Properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/68560159/142672006-6185b336-f964-426f-96ab-0a91826413c4.png)

**Other plugins**
i use nothing.

**Additional context**
Bottom Text. ***btw my school blocked discord and i'm runnin it in a iframe so don't worry about the url***

**Comment by TheRealGWJosh** [comment]
also if u have a discord server i wouldn't mind joining

**Comment by TheRealGWJosh** [comment]
![image](https://user-images.githubusercontent.com/68560159/142673143-9c28cc9f-8902-40ed-b904-b5f6dbe32f35.png)

if you have rounding vars that would be nice too i'll fix the rest

**Comment by Loremly** [comment]
Ill fix this immediately.. And a server isnt that bad....

**Comment by Loremly** [comment]
Solved in 5.3.8 Update. Please Update Nebula! Enjoy
