### ISSUE TITLE
Another One "Server Banners"

### ISSUE THREAD

**Issue by TheRealGWJosh** [Loremly/Nebula#12]
**Describe the bug**
Server Banners Misaligned

**To Reproduce**
1. Go to 'a Server With a Banner'
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/68560159/142674665-45ec193d-f198-4150-8d64-df2445876302.png)

**Additional context**
***i use web btw :kek:***

**Comment by Loremly** [comment]
1. Web is not supported yet. Dont even know how you got it to work on web. Please use the Discord app. You can get Discord Canary here; [MacOS](https://discord.com/api/download/canary?platform=osx) [Windows](https://discord.com/api/download/canary?platform=win) [Linux](https://discord.com/api/download/canary?platform=linux) [Linux(tar.gz)](https://discord.com/api/download/canary?platform=linux&format=tar.gz)

**Comment by Loremly** [comment]
Solved in 5.3.8 Update. Please Update Nebula! Enjoy
