### ISSUE TITLE
server banner

### ISSUE THREAD

**Issue by ElijahGives** [Loremly/Nebula#13]
**Describe the bug**
The banner hides channels (idk if its intentional.)

**To Reproduce**
1. Go to a  server with a banner
2. See that it hides a few channels

**Expected behavior**
it lets me see all channels by putting them under the banner.

**Screenshots**
![image](https://user-images.githubusercontent.com/57592789/142771893-063421ea-09e3-4000-a441-b6403f414fd0.png)

**Other plugins**
Do you have any enabled plugins that alter the functionality of Nebula
Plugins Enabled - BDFDB, BetterCodeBlocks, CustomStatusPresets, ImageUtilities, PermissionsViewer, PluginRepo, ReadAllNotificationsButton, RemoveBotTag, RoleMembers, ServerDetails, ShowHiddenChannels, SpellCheck, StaffTag, ThemeRepo, ZeresPluginLibrary
Themes Enabled - Better Badges, Nebula

**Additional context**

**Comment by Loremly** [comment]
Your ShowHiddenChannels might be the issue. Try disabling it.

**Comment by E-boi** [comment]
Might do the work

**Comment by ElijahGives** [comment]
fixed thanks.

**Comment by E-boi** [comment]
no problem! always here help!

**Comment by Loremly** [comment]
breh
