### ISSUE TITLE
Alternate Names Broken

### ISSUE THREAD

**Issue by TheRealGWJosh** [Loremly/Nebula#14]
**Describe the bug**

**To Reproduce**
1. Go to 'DM's'
2. Click on 'a Person With a Nickname in another server'
3. See error

**Expected behavior**
should be positioned right

**Screenshots**
![image](https://user-images.githubusercontent.com/68560159/143900701-8c8555c5-d38d-45d0-97b9-9eaa8269e9a5.png)

**Other plugins**
lol no

**Comment by TheRealGWJosh** [comment]
![image](https://user-images.githubusercontent.com/68560159/143900992-2edfc087-f064-4ead-bba6-5917a4f82208.png)

also server folders don't seem to be rounded right 🤔

**Comment by Loremly** [comment]
Are you using a specific OS?

**Comment by Loremly** [comment]
And please see if you updated Nebula

**Comment by TheRealGWJosh** [comment]
I use Chrome OS with stylus to load discord themes

**Comment by TheRealGWJosh** [comment]
also it still seems broken but then again i run this stuff on web
also how do you make issue templates i have no clue how and i want to do somthin like this but for my repo

**Comment by Loremly** [comment]
1. Web support is not supported yet.
2. Go to Insights > Community on your repository.
