### ISSUE TITLE
Server Settings menu unusable

### ISSUE THREAD

**Issue by sfarmani** [Loremly/Nebula#16]
**Describe the bug**
The server settings menu that pops up is unusable. Nothing can be clicked on, only the ESC hotkey works to get out of that menu. Its as if the I can click through the menu and click things behind it, like clicking a channel.

**To Reproduce**

Requires admin access to a server
1. Go to the server menu
2. Click on `server settings`
3. Try to click things

**Expected behavior**
I should be able to use the menu normally

**Info**
- OS: Windows 10
- Nebula verison: v5.9.28
- Enabled plugins: Better Codeblocks, Haste Paste, Message Translate, petpet, PinDMs, Plugin Downloader, Theme Downloader
- Enabled themes: Only Nebula

**Additional Information**
Do you have anything else you'd like to add before submitting?

When I take off the theme and use vanilla theme (on powercord still) I don't have this issue. Only with the Nebula theme it does this.
I did not add any custom code to the Nebula theme.

**Comment by Loremly** [comment]
I'm still in the process of renaming classes *mainly because im lazy* can you provide a screenshot of what element of nebula is troubling you so i can assess the issue when i finish

**Comment by sfarmani** [comment]
I made a gif if you don't mind, I didn't quite understand what elements you were asking for.
![preview](https://user-images.githubusercontent.com/15093212/149637302-0fb6cd4b-2d33-4a6c-84d8-4ccd5b84f213.gif)

**Comment by Loremly** [comment]
Thats reallllyy weird. You're using discord canary correct?

**Comment by sfarmani** [comment]
Yes, its up-to-date as well
discord canary without the theme works fine when going to server settings

**Comment by Loremly** [comment]
Personally I'm not experiencing this issue. Go through your plugins there might be something causing it. Or Canary is having issues.

**Comment by sfarmani** [comment]
Seems your latest changes on v5.10.0 fixed the issue, I guess I was a bit too early before you were able to fix all the class changes =[

Sorry for the inconvenience but everything seems to be working now!

**Comment by Loremly** [comment]
Alright great!
