### ISSUE TITLE
Little Tiny Mistake In Notes

### ISSUE THREAD

**Issue by Soft-Bred** [Loremly/Nebula#4]
in [_root.css](https://github.com/Loremly/Nebula/blob/main/src/_root.scss) the nice window notes aren't done correctly 

Mistake:
![image](https://user-images.githubusercontent.com/60551230/131606233-d7b98fea-c50b-45e3-bf70-06c795369daf.png)

What it should be:
![image](https://user-images.githubusercontent.com/60551230/131606273-5ca4c27b-82f0-4ddc-a8f4-900a0edeeb64.png)

**Comment by Loremly** [comment]
Fixed
