### ISSUE TITLE
Enabling streamer mode with server list and channels hidden breaks the server list

### ISSUE THREAD

**Issue by Flufiakojot** [Loremly/Nebula#7]
Here's what I mean by that;
After enabling streamer mode with servers and channels hidden
![image](https://user-images.githubusercontent.com/89755606/132016184-bf575c47-8a9b-4ab9-844f-c20a31572d29.png)
Hiding the server and channel list
![image](https://user-images.githubusercontent.com/89755606/132016207-1607308b-b721-4a5e-999a-4298bce7655f.png)

**Comment by Loremly** [comment]
This doesnt happen to me. Do you have any plugin that messes with streamer mode and/or server list?

**Comment by Flufiakojot** [comment]
Nah, I don't think so. But surprisingly it doesn't break today, I guess that could be a one-time bug.

**Comment by Loremly** [comment]
if it does happen tell me lol
