### ISSUE TITLE
OSX

### ISSUE THREAD

**Issue by doggybootsy** [Loremly/Nebula#8]
**Describe the bug**
The doesnt properly work on osx

**To Reproduce**
Use osx

**Expected behavior**

**Screenshots**
![Screen Shot 2021-09-12 at 12 07 02 PM](https://user-images.githubusercontent.com/71196819/132999744-ae92dd19-aea5-492b-a670-7742ce6b46fd.png)

**Other plugins**
no

**Additional context**
You can use the bd emulator plugin to fix it

**Comment by Loremly** [comment]
Will do! Can I have a link to the emulator plugin? Thanks

**Comment by doggybootsy** [comment]
Here's the link [https://betterdiscord.app/plugin/PlatformEmulator](https://betterdiscord.app/plugin/PlatformEmulator), and thanks that would be very nice

**Comment by doggybootsy** [comment]
Also this seems to happen on every os but windows
And Linux/web look the same

**Comment by Loremly** [comment]
Partially fixed!

**Comment by doggybootsy** [comment]
Thanks
