### ISSUE TITLE
Server role management panel is broken

### ISSUE THREAD

**Issue by Lighno** [Loremly/Nebula#9]
**Describe the bug**
Server role management panel has the role list in the middle of it

**To Reproduce**
1. Go to any server you moderate
2. Click on `server settings`
3. Click on `Roles`
4. Click on any role or default permissions 
5. See the default role list (unthemed) in the middle of the panel

**Expected behavior**
Clicking on a role lets you edit it

**Screenshots**
![image](https://user-images.githubusercontent.com/32402483/134434004-1acd449a-76ad-4be9-a1f5-384f8d7b612a.png)

**Other plugins**
None

**Additional context**
Not really related but the whole panel feels weird, maybe adding a back button to stop editing a role would help

**Comment by Loremly** [comment]
Thanks will check it out.
